# Site settings
title: RoboTribune
email: axel.voitier@gmail.com
author: Axel Voitier
description: "RoboTribune is a blog about the future of robotics and other connected devices written by Axel Voitier."
baseurl: ""
url: "http://www.robotribune.eu"
twitter_username: AxelVoitier
github_username: AxelVoitier
encoding: UTF-8

excerpt_separator: "\n\n\n"

lsi: true

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.atom"
    include_posts:
        - "/index.html"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
kramdown:
    input: GFM
destination: /tmp/_site

timezone: Europe/Paris
paginate: 10
        
post_images: /images/posts

defaults:
    - scope:
        path: ""
        type: "post"
      values:
        layout: "post"
        author: Axel Voitier
        priority: 0.75
        change_frequency: monthly
    - scope:
        path: ""
        type: "page"
      values:
        change_frequency: yearly
        priority: 0.60
